return
{
	int            = 0,
	bool           = 0,
	deathType      = 0,
	attackBits     = 0,
	teamColor      = 0,
	fullFlags      = 0,
	channelType    = 0,
	channelFlags   = 0,
	stackFlags     = 0,
	silenceFlags   = 0,
	spellDetail    = 0,
	detectionType  = 0,
	defenseTypeInt = 0,
	pickFlags      = 0,
	morphFlags     = 0,
	real           = 1,
	unreal         = 2,
}
